'use client';
import { motion } from 'framer-motion';
import { ArrowRight, CheckCircle2, Sparkles } from 'lucide-react';
import Link from 'next/link';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { Footer } from '@/components/layout/footer';

const features = ['Secure user profiles', 'Focused dashboard guidance', 'Future-ready AI module boundaries'];

export default function LandingPage() {
  return <main className="min-h-screen overflow-hidden bg-[radial-gradient(circle_at_top_left,rgba(52,120,246,.24),transparent_34rem),radial-gradient(circle_at_80%_20%,rgba(34,211,238,.14),transparent_28rem),#020617]"><section className="relative px-6 py-8"><nav className="mx-auto flex max-w-6xl items-center justify-between"><Link className="flex items-center gap-3 font-bold" href="/"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-brand-500">AI</span>Career Mentor Agent</Link><div className="flex items-center gap-3"><Link className="hidden rounded-xl px-4 py-2 text-sm text-slate-300 hover:bg-white/10 sm:block" href="/login">Sign in</Link><Link href="/register"><Button className="px-4 py-2">Get started</Button></Link></div></nav><div className="mx-auto grid max-w-6xl gap-10 py-20 lg:grid-cols-[1.05fr_.95fr] lg:py-28"><motion.div initial={{ opacity: 0, y: 24 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.6 }}><Badge><Sparkles size={14} /> Premium SaaS foundation</Badge><h1 className="mt-6 text-5xl font-black tracking-tight md:text-7xl">A calm command center for your next career move.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-300">Create a secure profile, organize career goals, and prepare for future AI mentorship workflows in a focused, modern workspace.</p><div className="mt-8 flex flex-col gap-4 sm:flex-row"><Link href="/register"><Button>Create free account <ArrowRight size={18} /></Button></Link><Link className="rounded-xl border border-white/10 px-5 py-3 text-center font-semibold text-slate-200 transition hover:bg-white/10" href="/login">Open dashboard</Link></div></motion.div><motion.div initial={{ opacity: 0, scale: 0.96 }} animate={{ opacity: 1, scale: 1 }} transition={{ delay: 0.15, duration: 0.6 }}><Card className="relative overflow-hidden"><div className="absolute right-6 top-6 h-24 w-24 rounded-full bg-brand-500/20 blur-3xl" /><p className="text-sm text-slate-400">Workspace preview</p><h2 className="mt-2 text-2xl font-bold">Career Profile OS</h2><div className="mt-6 space-y-3">{features.map((feature) => <div className="flex items-center gap-3 rounded-2xl bg-white/[0.06] p-4 text-slate-200" key={feature}><CheckCircle2 className="text-brand-50" size={18} />{feature}</div>)}</div><div className="mt-6 rounded-3xl bg-gradient-to-br from-brand-500/30 to-cyan-300/10 p-5"><p className="text-sm text-slate-300">No fake charts. No noisy dashboards. Just meaningful profile data and next actions.</p></div></Card></motion.div></div></section><Footer /></main>;
}
