import { Injectable } from '@nestjs/common';
import { AiProviderService } from '../ai/providers/ai-provider.service';
import { PrismaService } from '../common/prisma.service';
import { GenerateQuestionsDto, SaveInterviewSessionDto } from './dto/interview.dto';
type Questions = { questions: { question:string; expectedAnswer?:string; tags?:string[] }[]; feedback?: { summary:string; improvementSuggestions:string[]; learningRecommendations:string[]; performanceScore:number; confidenceScore:number } };
@Injectable()
export class InterviewService { constructor(private prisma: PrismaService, private ai: AiProviderService) {}
async generate(userId:string,dto:GenerateQuestionsDto){ const ctx=await this.context(userId); const result=await this.ai.generateJson<Questions>(`Generate 8 ${dto.difficulty} ${dto.type} interview questions for ${dto.targetRole ?? ctx.user?.careerGoal ?? 'the user career goal'}. Use resume/career context: ${JSON.stringify(ctx)}. Return JSON {"questions":[{"question":"...","expectedAnswer":"...","tags":[""]}],"feedback":{"summary":"","improvementSuggestions":[],"learningRecommendations":[],"performanceScore":0,"confidenceScore":0}}`); return result; }
async save(userId:string,dto:SaveInterviewSessionDto){ const generated = dto.questions?.length ? { questions: dto.questions as any[] } : await this.generate(userId,dto); const feedback = await this.ai.generateJson<any>(`Evaluate this mock interview. Type ${dto.type}, difficulty ${dto.difficulty}, role ${dto.targetRole}. Questions/answers: ${JSON.stringify({questions: generated.questions, answers: dto.answers ?? []})}. Return JSON with summary, improvementSuggestions, learningRecommendations, performanceScore, confidenceScore.`); return this.prisma.interviewSession.create({ data:{ userId, type:dto.type, difficulty:dto.difficulty, targetRole:dto.targetRole, summary:dto.summary ?? feedback.summary, performanceScore: feedback.performanceScore ?? dto.performanceScore ?? 0, confidenceScore: feedback.confidenceScore ?? dto.confidenceScore ?? 0, feedback, questions:{ create: (generated.questions ?? []).map((q:any)=>({ type:dto.type, difficulty:dto.difficulty, question:String(q.question), expectedAnswer:q.expectedAnswer, tags:q.tags ?? [] }))}}, include:{questions:true, feedbackItems:true} }); }
list(userId:string){ return this.prisma.interviewSession.findMany({ where:{userId}, orderBy:{createdAt:'desc'}, include:{questions:true} }); }
private async context(userId:string){ const [user, profile, resume, ats]=await Promise.all([this.prisma.user.findUnique({where:{id:userId}}),this.prisma.careerProfile.findUnique({where:{userId}}),this.prisma.resume.findFirst({where:{userId},orderBy:{createdAt:'desc'}}),this.prisma.resumeAnalysis.findFirst({where:{userId},orderBy:{createdAt:'desc'}})]); return {user,profile,resume,ats}; }}
