'use client';
import Link from 'next/link';
import { BookOpen, GraduationCap, Sparkles, Target, UserRound } from 'lucide-react';
import { useAuth } from '@/components/auth/auth-context';
import { EmptyState } from '@/components/ui/empty-state';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { Skeleton } from '@/components/ui/skeleton';
import { StatCard } from '@/components/shared/stat-card';

export default function DashboardPage() {
  const { user, isLoading } = useAuth();
  if (isLoading) return <main className="grid gap-6 p-6 md:grid-cols-2 xl:grid-cols-4"><Skeleton className="h-48 md:col-span-2 xl:col-span-4" />{Array.from({ length: 4 }).map((_, index) => <Skeleton className="h-44" key={index} />)}</main>;
  const missingProfile = !user?.education && !user?.careerGoal && !user?.currentSkills;
  return <main className="space-y-6 p-4 md:p-6"><section className="overflow-hidden rounded-[2rem] border border-white/10 bg-gradient-to-br from-white/[0.12] to-white/[0.03] p-6 shadow-2xl md:p-8"><div className="flex flex-col gap-6 lg:flex-row lg:items-center lg:justify-between"><div><p className="inline-flex rounded-full border border-brand-500/30 bg-brand-500/10 px-3 py-1 text-sm text-brand-50">Premium career workspace</p><h2 className="mt-5 text-3xl font-black tracking-tight md:text-5xl">Build your next career move with clarity.</h2><p className="mt-4 max-w-2xl text-slate-300">Your dashboard now focuses on verified account data, profile completeness, and practical next actions without fake analytics.</p></div><Link href="/dashboard/profile/edit"><Button><Sparkles size={18} /> Complete profile</Button></Link></div></section><div className="grid gap-6 md:grid-cols-2 xl:grid-cols-4"><StatCard helper="This is the name shown across your workspace." icon={<UserRound size={20} />} title="User Profile" value={user?.fullName} /><StatCard helper="Define the role or path you are working toward." icon={<Target size={20} />} title="Career Goal" value={user?.careerGoal} /><StatCard helper="Keep your strongest skills current for future recommendations." icon={<BookOpen size={20} />} title="Current Skills" value={user?.currentSkills} /><StatCard helper="Education context helps personalize later experiences." icon={<GraduationCap size={20} />} title="Education" value={user?.education} /></div><div className="grid gap-6 xl:grid-cols-[1.1fr_.9fr]"><Card><h3 className="text-xl font-bold">Recent Activity</h3>{missingProfile ? <EmptyState title="No activity yet" description="Your account is ready. Complete your profile to create meaningful activity in future phases." /> : <div className="mt-5 space-y-3"><div className="rounded-2xl bg-white/[0.05] p-4"><p className="font-medium">Profile available</p><p className="mt-1 text-sm text-slate-400">Your authenticated profile is being loaded from the backend.</p></div></div>}</Card><Card><h3 className="text-xl font-bold">Quick Actions</h3><div className="mt-5 grid gap-3"><Link className="rounded-2xl border border-white/10 bg-white/[0.05] p-4 transition hover:bg-white/10" href="/dashboard/profile/edit">Update profile details</Link><Link className="rounded-2xl border border-white/10 bg-white/[0.05] p-4 transition hover:bg-white/10" href="/dashboard/settings">Review account settings</Link><div className="rounded-2xl border border-dashed border-white/10 p-4 text-slate-500">AI features unlock in later phases</div></div></Card></div></main>;
}
