import { Body, Controller, Delete, Get, Param, Patch, Post, Query, Req, UseGuards } from '@nestjs/common';
import { ApiBearerAuth, ApiTags } from '@nestjs/swagger';
import { JwtAuthGuard } from '../auth/guards/jwt-auth.guard';
import { apiResponse } from '../common/api-response';
import { AuthenticatedRequest } from '../common/types/authenticated-request';
import { GoalDto, JobDto, MilestoneDto, NotificationDto } from './dto/productivity.dto';
import { ProductivityService } from './productivity.service';
@ApiTags('Career Productivity') @ApiBearerAuth() @UseGuards(JwtAuthGuard) @Controller('productivity')
export class ProductivityController{constructor(private s:ProductivityService){}
@Post('jobs') createJob(@Req()r:AuthenticatedRequest,@Body()d:JobDto){return this.s.createJob(r.user.sub,d).then(x=>apiResponse('Job application created.',x))}@Get('jobs') jobs(@Req()r:AuthenticatedRequest,@Query('search')q?:string,@Query('status')st?:any){return this.s.listJobs(r.user.sub,q,st).then(x=>apiResponse('Job applications retrieved.',x))}@Patch('jobs/:id') updJob(@Req()r:AuthenticatedRequest,@Param('id')id:string,@Body()d:JobDto){return this.s.updateJob(r.user.sub,id,d).then(x=>apiResponse('Job application updated.',x))}@Delete('jobs/:id') delJob(@Req()r:AuthenticatedRequest,@Param('id')id:string){return this.s.deleteJob(r.user.sub,id).then(x=>apiResponse('Job application deleted.',x))}
@Get('resources') resources(@Query('type')type?:string){return this.s.resources(type).then(x=>apiResponse('Career resources retrieved.',x))}
@Post('goals') createGoal(@Req()r:AuthenticatedRequest,@Body()d:GoalDto){return this.s.createGoal(r.user.sub,d).then(x=>apiResponse('Goal created.',x))}@Get('goals') goals(@Req()r:AuthenticatedRequest){return this.s.listGoals(r.user.sub).then(x=>apiResponse('Goals retrieved.',x))}@Patch('goals/:id') updGoal(@Req()r:AuthenticatedRequest,@Param('id')id:string,@Body()d:GoalDto){return this.s.updateGoal(r.user.sub,id,d).then(x=>apiResponse('Goal updated.',x))}@Delete('goals/:id') delGoal(@Req()r:AuthenticatedRequest,@Param('id')id:string){return this.s.deleteGoal(r.user.sub,id).then(x=>apiResponse('Goal deleted.',x))}@Post('goals/:id/milestones') ms(@Req()r:AuthenticatedRequest,@Param('id')id:string,@Body()d:MilestoneDto){return this.s.addMilestone(r.user.sub,id,d).then(x=>apiResponse('Milestone saved.',x))}
@Get('notifications') notifications(@Req()r:AuthenticatedRequest){return this.s.notifications(r.user.sub).then(x=>apiResponse('Notifications retrieved.',x))}@Post('notifications') notify(@Req()r:AuthenticatedRequest,@Body()d:NotificationDto){return this.s.notify(r.user.sub,d).then(x=>apiResponse('Notification created.',x))}@Patch('notifications/:id/read') read(@Req()r:AuthenticatedRequest,@Param('id')id:string){return this.s.readNotification(r.user.sub,id).then(x=>apiResponse('Notification read.',x))}}
